language: php

php:
  - "7.2"

cache:
  directories:
    - "./vendor"

dist: trusty

before_script:
  - composer install --no-interaction

script:
  # - vendor/bin/phpunit
  - docker build -t siwecos-crawler .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: develop
    script: >-
      docker tag siwecos-crawler siwecos/siwecos-crawler:develop &&
      docker push siwecos/siwecos-crawler:develop
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: >-
      docker tag siwecos-crawler siwecos/siwecos-crawler:latest &&
      docker push siwecos/siwecos-crawler:latest
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: >-
      docker tag siwecos-crawler siwecos/siwecos-crawler:$TRAVIS_TAG &&
      docker push siwecos/siwecos-crawler:$TRAVIS_TAG
